filters:
  include_keywords:
    - "Director"
    - "Enrollment"
    - "CRM"
    - "Admissions"
    - "Marketing"
    - "Data"
  exclude_keywords:
    - "Intern"
    - "Faculty"
    - "Assistant Professor"
  locations:
    - "Remote"
    - "Massachusetts"
    - "Vermont"
    - "Maine"
    - "Pennsylvania"
  salary_min: 70000
  staleness_days: 14

sources:
  - type: rss
    name: HigherEdJobs Enrollment
    url: "https://www.higheredjobs.com/rss/enrollment.xml"
  - type: rss
    name: HigherEdJobs Marketing
    url: "https://www.higheredjobs.com/rss/marketing.xml"
  - type: rss
    name: HigherEdJobs Remote
    url: "https://www.higheredjobs.com/rss/remote.xml"

notify:
  enabled: false


scheduler:
  cron: "0 8 * * *"      # 8:00 AM daily
